"""Deep topic pools organized by category.

Each pool targets 40+ entries with a security, math, or architecture tilt.
Topics are atomic subjects — the randomizer combines them with modifiers
and cross-pollinates across categories.
"""

from __future__ import annotations

from atomics.models import TaskCategory

TOPIC_POOLS: dict[TaskCategory, list[str]] = {
    TaskCategory.WEB_SUMMARY: [
        "WebAssembly adoption in production backends",
        "eBPF for kernel-level observability",
        "QUIC protocol vs TCP in adversarial networks",
        "Rust in Linux kernel development and memory safety guarantees",
        "Supply chain security for container base images",
        "Zero-trust architecture in hybrid cloud environments",
        "gRPC vs REST for microservice communication under load",
        "Database sharding strategies for globally distributed systems",
        "Edge computing with Cloudflare Workers vs Lambda@Edge",
        "Service mesh: Istio vs Linkerd vs Cilium performance profiles",
        "HTTP/3 adoption and its impact on TLS handshake latency",
        "Sigstore and keyless signing for software artifacts",
        "SPIFFE/SPIRE for workload identity in Kubernetes",
        "Merkle tree structures in certificate transparency logs",
        "Content-addressable storage and its security properties",
        "Homomorphic encryption libraries: practical performance in 2025",
        "Differential privacy in federated learning pipelines",
        "Post-quantum TLS: lattice-based key exchange in practice",
        "BPF LSM hooks for runtime security policy enforcement",
        "io_uring and its attack surface in Linux kernels",
        "Capabilities-based security models vs traditional DAC/MAC",
        "Memory tagging extensions (MTE) on ARM architectures",
        "Confidential computing with AMD SEV and Intel TDX",
        "WASI preview 2 and the component model security boundaries",
        "Formal verification of cryptographic protocols with ProVerif",
        "Gossip protocols and their consistency guarantees",
        "CRDTs for conflict-free replicated security audit logs",
        "Bloom filters for probabilistic intrusion detection",
        "Erasure coding vs replication for fault-tolerant storage",
        "The CAP theorem revisited: PACELC and real-world trade-offs",
        "Raft consensus under network partitions",
        "Vector clocks and causal ordering in distributed logs",
        "Wireguard protocol design and its cryptographic choices",
        "DNS-over-HTTPS privacy implications and threat model",
        "Certificate pinning strategies in mobile applications",
        "SBOM generation and consumption in CI/CD pipelines",
        "Reproducible builds and their role in supply chain integrity",
        "Immutable infrastructure patterns and drift detection",
        "GitOps security: signed commits and policy-as-code",
        "OpenTelemetry security considerations in multi-tenant systems",
    ],
    TaskCategory.RESEARCH: [
        "SQLite vs DuckDB for embedded analytical workloads",
        "Kubernetes operators vs Helm charts for stateful deployments",
        "LLM quantization: GPTQ vs AWQ vs GGUF accuracy trade-offs",
        "WASM runtimes: Wasmtime vs Wasmer vs WasmEdge sandboxing",
        "Event sourcing vs CRUD: consistency and auditability comparison",
        "Vector databases: Pinecone vs Milvus vs pgvector performance",
        "Multi-tenant SaaS on Kubernetes: namespace vs cluster isolation",
        "Kafka vs Pulsar vs Redpanda: exactly-once semantics comparison",
        "RBAC vs ABAC vs ReBAC authorization model trade-offs",
        "Container runtimes: containerd vs CRI-O vs gVisor security posture",
        "Consistent hashing algorithms: jump hash vs ring hash vs maglev",
        "LSM-tree vs B-tree storage engines for write-heavy workloads",
        "Paxos vs Raft vs EPaxos: latency and fault tolerance comparison",
        "Zero-knowledge proofs: zk-SNARKs vs zk-STARKs practical trade-offs",
        "Secure enclaves: SGX vs TrustZone vs SEV threat models",
        "Time-series databases: TimescaleDB vs InfluxDB vs QuestDB",
        "Graph databases for attack path analysis: Neo4j vs TigerGraph",
        "Fuzzing strategies: coverage-guided vs grammar-based vs hybrid",
        "Static analysis tools: Semgrep vs CodeQL vs Snyk Code comparison",
        "eBPF vs kernel modules for network security monitoring",
        "Chaos engineering platforms: Litmus vs Chaos Mesh vs Gremlin",
        "Policy engines: OPA vs Cedar vs Casbin expressiveness comparison",
        "Secret managers: Vault vs AWS Secrets Manager vs SOPS trade-offs",
        "mTLS implementations: Envoy vs Linkerd proxy vs application-level",
        "Database encryption: TDE vs column-level vs application-layer",
        "Log aggregation architectures: ELK vs Loki vs ClickHouse",
        "Network segmentation: VLANs vs microsegmentation vs zero-trust",
        "Immutable OS designs: NixOS vs Flatcar vs Bottlerocket",
        "Sandboxing technologies: seccomp-bpf vs Landlock vs pledge/unveil",
        "Elliptic curve selection: P-256 vs Curve25519 vs secp256k1",
        "Hash function properties: SHA-3 vs BLAKE3 vs SHA-256 performance",
        "Key derivation: Argon2 vs scrypt vs bcrypt parameter tuning",
        "Load balancing algorithms: least connections vs P2C vs EWMA",
        "Rate limiting algorithms: token bucket vs leaky bucket vs sliding window",
        "Circuit breaker implementations: Hystrix patterns vs Envoy vs custom",
        "Garbage collection strategies: G1 vs ZGC vs Shenandoah pause analysis",
        "Memory allocators: jemalloc vs mimalloc vs tcmalloc fragmentation",
        "Lock-free data structures: CAS operations and ABA problem mitigations",
        "Persistent data structures and their applications in audit systems",
        "Probabilistic data structures: HyperLogLog vs Count-Min Sketch uses",
    ],
    TaskCategory.SECURITY_NEWS: [
        "XZ Utils backdoor and the fragility of open-source trust chains",
        "HTTP/2 rapid reset DDoS amplification vector",
        "OAuth 2.0 token theft via open redirect chaining",
        "Container escape via runc CVE and kernel namespace breakout",
        "DNS rebinding attacks against cloud metadata services",
        "Prompt injection in LLM-integrated applications and guardrail bypasses",
        "SSRF against cloud metadata endpoints (169.254.169.254)",
        "Kubernetes RBAC wildcard misconfigurations",
        "Typosquatting campaigns in PyPI and npm registries",
        "JWT algorithm confusion and key confusion attacks",
        "Deserialization vulnerabilities in Java and .NET frameworks",
        "Race condition exploits in filesystem operations (TOCTOU)",
        "Spectre/Meltdown variant attacks and microarchitectural side channels",
        "Rowhammer and its implications for cloud multi-tenancy",
        "BGP hijacking and prefix spoofing in internet routing",
        "TLS downgrade attacks: DROWN, POODLE, and Logjam",
        "SAML assertion manipulation and XML signature wrapping",
        "Kerberoasting and AS-REP roasting in Active Directory",
        "Golden ticket and silver ticket attacks in Kerberos",
        "Pass-the-hash and pass-the-ticket credential attacks",
        "Subdomain takeover via dangling DNS records",
        "Dependency confusion attacks in private package registries",
        "Prototype pollution in JavaScript applications",
        "GraphQL introspection abuse and batched query attacks",
        "WebSocket hijacking and cross-site WebSocket abuse",
        "Server-side template injection (SSTI) across frameworks",
        "Blind SSRF exploitation via timing side channels",
        "HTTP request smuggling via CL.TE and TE.CL desync",
        "CORS misconfigurations enabling credential theft",
        "CSP bypass techniques: dangling markup and script gadgets",
        "Insecure direct object reference (IDOR) patterns in REST APIs",
        "Mass assignment vulnerabilities in ORM frameworks",
        "NoSQL injection in MongoDB and DynamoDB query construction",
        "XXE injection in XML parsers across languages",
        "Padding oracle attacks against CBC-mode encryption",
        "Timing attacks on comparison functions and HMAC verification",
        "Cache poisoning via HTTP header manipulation",
        "DNS cache poisoning and the Kaminsky attack evolution",
        "Supply chain attacks via compromised CI/CD pipelines",
        "Firmware implants and UEFI rootkit persistence mechanisms",
    ],
    TaskCategory.PATTERN_EXTRACTION: [
        "Retry and circuit-breaker patterns in distributed systems",
        "Secret management patterns across CI/CD pipeline stages",
        "API versioning strategies and backward compatibility patterns",
        "Infrastructure-as-code testing: unit, integration, and policy tests",
        "Observability anti-patterns in microservice architectures",
        "Zero-downtime database migration patterns",
        "Secure defaults in Terraform and CloudFormation provisioning",
        "Rate limiting and adaptive throttling for public APIs",
        "Bulkhead isolation patterns for fault containment",
        "Saga pattern vs two-phase commit in distributed transactions",
        "Sidecar proxy patterns for security policy enforcement",
        "Strangler fig pattern for incremental legacy migration",
        "Event-driven architecture anti-patterns and ordering guarantees",
        "Idempotency patterns for exactly-once processing",
        "Blue-green and canary deployment security considerations",
        "Feature flag patterns and their security implications",
        "Multi-region failover patterns with data sovereignty",
        "Backpressure patterns in stream processing systems",
        "Dead letter queue patterns for poison message handling",
        "Connection pooling patterns and pool exhaustion attacks",
        "Token rotation patterns for credential lifecycle management",
        "Audit log patterns: append-only, tamper-evident, and compliant",
        "Encryption key rotation patterns across distributed systems",
        "Certificate lifecycle automation patterns with ACME",
        "Ingress security patterns: WAF rules, bot detection, DDoS mitigation",
        "Container image scanning patterns in CI/CD pipelines",
        "Network policy patterns in Kubernetes: deny-all-first approach",
        "Secrets injection patterns: env vars vs mounted volumes vs CSI drivers",
        "Chaos testing patterns: steady-state hypothesis and blast radius control",
        "Configuration drift detection and remediation patterns",
        "Immutable deployment patterns and rollback strategies",
        "Service account least-privilege patterns in cloud IAM",
        "Mutual TLS bootstrap patterns in service mesh architectures",
        "Data classification patterns for privacy-by-design systems",
        "Incident response automation patterns: SOAR playbooks",
        "Log correlation patterns across distributed tracing spans",
        "Cache invalidation patterns and their consistency trade-offs",
        "Graceful degradation patterns under partial system failure",
        "Health check patterns: liveness, readiness, and startup probes",
        "Queue-based load leveling patterns for bursty workloads",
    ],
    TaskCategory.GENERAL_QA: [
        "What is the CAP theorem and when does it actually matter?",
        "How does TLS 1.3 eliminate round trips compared to 1.2?",
        "What are the OWASP Top 10 for 2025 and what changed?",
        "Explain the difference between symmetric and asymmetric encryption",
        "What is a race condition and name three mitigation strategies",
        "How does memory-safe language adoption reduce CVE counts?",
        "What are the trade-offs between monorepo and polyrepo strategies?",
        "How do you implement mutual TLS between microservices?",
        "Explain the principle of least privilege in cloud IAM design",
        "How does eBPF improve kernel-level security monitoring?",
        "What is the halting problem and why does it matter for static analysis?",
        "Explain Lamport timestamps and vector clocks",
        "What is the Byzantine generals problem and its solutions?",
        "How does Shamir's secret sharing work mathematically?",
        "Explain the birthday paradox and its relevance to hash collisions",
        "What is the difference between safety and liveness in distributed systems?",
        "How does Dijkstra's algorithm differ from A* in pathfinding?",
        "Explain the P vs NP problem and its implications for cryptography",
        "What is entropy in the context of random number generation?",
        "How does a Bloom filter work and what are its false positive guarantees?",
        "Explain the pigeonhole principle and its use in security proofs",
        "What is the coupon collector's problem and where does it appear in systems?",
        "How does consistent hashing minimize key redistribution?",
        "Explain the concept of semantic security in encryption schemes",
        "What is forward secrecy and why is it important for TLS?",
        "How does a Merkle tree enable efficient data integrity verification?",
        "Explain Little's law and its application to system capacity planning",
        "What is the Swiss cheese model of security failures?",
        "How does the exponential backoff algorithm prevent thundering herds?",
        "Explain the difference between authentication and authorization",
        "What is defense in depth and how do you implement it concretely?",
        "How does public key infrastructure (PKI) establish trust chains?",
        "Explain the Dolev-Yao model for analyzing cryptographic protocols",
        "What is the difference between confusion and diffusion in block ciphers?",
        "How do you calculate the work factor for a brute-force attack?",
        "Explain Amdahl's law and its implications for parallel security scanning",
        "What is the Needham-Schroeder protocol and its known vulnerabilities?",
        "How does a hardware security module (HSM) protect cryptographic keys?",
        "Explain the concept of indistinguishability in encryption security proofs",
        "What is the difference between a MAC and a digital signature?",
    ],
}

# Secondary topics for cross-pollination combinatorics
CROSS_POLLINATION_TOPICS = [
    "formal verification methods",
    "information-theoretic bounds",
    "adversarial machine learning",
    "Byzantine fault tolerance",
    "queueing theory",
    "graph theory in network security",
    "game-theoretic security models",
    "cryptographic commitment schemes",
    "zero-knowledge proof systems",
    "lattice-based cryptography",
    "side-channel resistance",
    "memory safety guarantees",
    "type-theoretic approaches",
    "category theory in software design",
    "Kolmogorov complexity",
    "information entropy",
    "Markov chain analysis",
    "linear algebra in machine learning security",
    "number theory in public-key cryptography",
    "probability theory in anomaly detection",
    "control theory in autoscaling systems",
    "signal processing in network traffic analysis",
    "topology in distributed system design",
    "lambda calculus in type-safe APIs",
    "abstract algebra in error-correcting codes",
]
